vich_uploader:
    db_driver: orm

    mappings:
        poster_file:
           uri_prefix: /uploads/posters
           upload_destination: '%kernel.project_dir%/public/uploads/posters'
           inject_on_load : false
           delete_on_update : true
           delete_on_remove : true
           namer: Vich\UploaderBundle\Naming\UniqidNamer

        picture_file:
          uri_prefix: /uploads/pictures
          upload_destination: '%kernel.project_dir%/public/uploads/pictures'
          inject_on_load : false
          delete_on_update : true
          delete_on_remove : true
          namer: Vich\UploaderBundle\Naming\UniqidNamer
